.TH "ARTSCAT" "1" 
.SH "NAME" 
artscat \(em pipe data to sound device 
.SH "SYNOPSIS" 
.PP 
\fBartscat\fR [\fB\fI options \fR\fP]  [\fB\fI filename \fR\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBartscat\fR command. 
.PP 
\fBartscat\fR pipes data from a pipe to the sound device through arts. 
.SH "OPTIONS" 
.PP 
This program follows the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. 
.IP "\fB-b \fIbits\fR\fP         " 10 
set number of bits (8 or 16) 
.IP "\fB-c \fIchannels\fR\fP         " 10 
set number of channels (1 or 2) 
.IP "\fB-h\fP         " 10 
display help and exit 
.IP "\fB-r \fIsamplingrate\fR\fP         " 10 
set samplingrate to use 
.IP "\fB-t \fItitle\fR\fP         " 10 
set stream title 
.IP "\fB-v\fP         " 10 
show version 
.SH "AUTHOR" 
.PP 
This manual page was written by Chris Cheney 
<ccheney@debian.org> for the \fBDebian\fP system (but may be used by 
others).  Permission is granted to copy, distribute and/or 
modify this document under the terms of the GNU General Public 
License, Version 2 or any later version published by the Free 
Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General 
Public License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man 
